version: '2'
services:
    api01:
      build: ./api
      image: "offset-tracker-api"
      container_name: 'offset_api01'
      volumes:
        - ./api:/usr/src/app:rw
        - /usr/src/app/node_modules
        - /etc/localtime:/etc/localtime:ro
        - /data/docker-persist/offset-tracker/api01/logs:/usr/src/app/output_logs:rw
      environment:
        NODE_ENV: ${NODE_ENV}
      expose:
        - "3000"
      restart: always

    api02:
      image: offset-tracker-api:latest
      container_name: 'offset_api02'
      volumes:
        - ./api:/usr/src/app:rw
        - /usr/src/app/node_modules
        - /etc/localtime:/etc/localtime:ro
        - /data/docker-persist/offset-tracker/api02/logs:/usr/src/app/output_logs:rw
      environment:
        NODE_ENV: ${NODE_ENV}
      expose:
        - "3000"
      restart: always

    api03:
      image: offset-tracker-api:latest
      container_name: 'offset_api03'
      volumes:
        - ./api:/usr/src/app:rw
        - /usr/src/app/node_modules
        - /etc/localtime:/etc/localtime:ro
        - /data/docker-persist/offset-tracker/api03/logs:/usr/src/app/output_logs:rw
      environment:
        NODE_ENV: ${NODE_ENV}
      expose:
        - "3000"
      restart: always

    haproxy:
      build: ./haproxy
      container_name: 'offset_api_haproxy'
      volumes:
        - /etc/localtime:/etc/localtime:ro
      links:
        - api01
        - api02
        - api03
      ports:
        - "8087:8087"
        - "1943:1943"
      restart: always
